export interface Property {
  id: number
  title: string
  district: string
  rooms: string
  area: number
  price: number
  image: string
  type: "sale" | "rent"
  hot?: boolean
  description: string
  features: string[]
}

export const properties: Property[] = [
  {
    id: 1,
    title: "Prestige Residence",
    district: "Mezitli",
    rooms: "1+1",
    area: 65,
    price: 55000,
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop",
    type: "sale",
    hot: true,
    description: "Современная квартира в престижном комплексе с видом на море.",
    features: ["Бассейн", "Фитнес-зал", "Парковка", "Сауна"],
  },
  {
    id: 2,
    title: "Marina Tower",
    district: "Yenisehir",
    rooms: "2+1",
    area: 110,
    price: 95000,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    type: "sale",
    hot: true,
    description: "Просторная квартира в центре города с панорамным видом.",
    features: ["Терраса", "Центральное отопление", "Парковка", "Консьерж"],
  },
  {
    id: 3,
    title: "Sea Breeze Apartments",
    district: "Tomuk",
    rooms: "3+1",
    area: 145,
    price: 130000,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    type: "sale",
    hot: true,
    description: "Просторный пентхаус на первой линии с прямым доступом к пляжу.",
    features: ["Первая линия", "Терраса", "Бассейн", "Детская площадка"],
  },
  {
    id: 4,
    title: "Palm Garden",
    district: "Erdemli",
    rooms: "2+1",
    area: 90,
    price: 72000,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop",
    type: "sale",
    hot: true,
    description: "Уютная квартира в зеленом районе рядом с морем.",
    features: ["Сад", "Бассейн", "Парковка", "Детская площадка"],
  },
  {
    id: 5,
    title: "Sunset Villa",
    district: "Mezitli",
    rooms: "4+1",
    area: 220,
    price: 250000,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&h=400&fit=crop",
    type: "sale",
    description: "Роскошная вилла с собственным садом и бассейном.",
    features: ["Частный бассейн", "Сад", "Гараж", "Барбекю"],
  },
  {
    id: 6,
    title: "City Center Studio",
    district: "Yenisehir",
    rooms: "1+0",
    area: 45,
    price: 38000,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop",
    type: "sale",
    description: "Компактная студия в самом центре Мерсина.",
    features: ["Меблированная", "Кондиционер", "Лифт", "Охрана"],
  },
  {
    id: 7,
    title: "Coastal Apartment",
    district: "Tomuk",
    rooms: "2+1",
    area: 95,
    price: 85000,
    image: "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=600&h=400&fit=crop",
    type: "sale",
    description: "Квартира с видом на Средиземное море в новом комплексе.",
    features: ["Вид на море", "Бассейн", "Тренажерный зал", "Сауна"],
  },
  {
    id: 8,
    title: "Green Valley",
    district: "Erdemli",
    rooms: "3+1",
    area: 130,
    price: 115000,
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&h=400&fit=crop",
    type: "sale",
    description: "Семейная квартира в экологически чистом районе.",
    features: ["Зеленая территория", "Детская площадка", "Парковка", "Охрана"],
  },
  // Rent properties
  {
    id: 101,
    title: "Cozy Studio Rent",
    district: "Yenisehir",
    rooms: "1+0",
    area: 40,
    price: 350,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop",
    type: "rent",
    description: "Уютная студия для аренды в центре города.",
    features: ["Меблированная", "Wi-Fi", "Кондиционер"],
  },
  {
    id: 102,
    title: "Seaside Rental",
    district: "Mezitli",
    rooms: "2+1",
    area: 85,
    price: 600,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop",
    type: "rent",
    description: "Квартира у моря для длительной аренды.",
    features: ["Вид на море", "Меблированная", "Парковка", "Бассейн"],
  },
  {
    id: 103,
    title: "Family Home Rent",
    district: "Tomuk",
    rooms: "3+1",
    area: 120,
    price: 850,
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&h=400&fit=crop",
    type: "rent",
    description: "Просторная квартира для семьи рядом с школой и парком.",
    features: ["Рядом школа", "Парк", "Меблированная", "Балкон"],
  },
  {
    id: 104,
    title: "Luxury Penthouse Rent",
    district: "Yenisehir",
    rooms: "4+1",
    area: 200,
    price: 1500,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&h=400&fit=crop",
    type: "rent",
    description: "Пентхаус класса люкс с панорамным видом на город и море.",
    features: ["Панорамный вид", "Терраса", "Джакузи", "Консьерж"],
  },
]
